### ISSUE TITLE
sqlite3DbMallocRawNN crashes

### ISSUE THREAD

**Issue by jengelh** [grommunio/gromox#63]
sqlite-3.39.3

```
$ gdb gxhttp core
Program terminated with signal SIGSEGV, Segmentation fault.
#0  sqlite3DbMallocRawNN (db=0x7f4468e17260, n=2) at sqlite3.c:29402
29402         db->lookaside.pSmallFree = pBuf->pNext;
[Current thread is 1 (Thread 0x7f4500fec700 (LWP 9197))]
(gdb) p db->lookaside
$1 = {bDisable = 0, sz = 1200, szTrue = 1200, bMalloced = 1 '\001', nSlot = 123, anStat = {1810951888, 131802, 11678636}, pInit = 0x0, 
  pFree = 0x7f447c0ac2b0, pSmallInit = 0x0, pSmallFree = 0x7f006e69616d, pMiddle = 0x7f447c0afaf0, pStart = 0x7f447c0a6e50, pEnd = 0x7f447c0b2970}

#0  sqlite3DbMallocRawNN (db=0x7f4468e17260, n=2) at sqlite3.c:29402
#1  0x00007f451db7e9ba in sqlite3DbStrNDup (db=<optimized out>, z=z@entry=0x7f4500fea03f "D", n=1) at sqlite3.c:29521
#2  0x00007f451db7ea36 in vdbeChangeP4Full (p=0x7f447c0aa1e0, pOp=0x7f447c0aa750, zP4=0x7f4500fea03f "D", n=<optimized out>) at sqlite3.c:82084
```
pSmallFree is garbage for some reason.

**Comment by jengelh** [comment]
What can I say, try sqlite-3.42.
